# $Id: docker-compose.yml v.0.5 $ $Date: 2018/05/10 $ $Author: GB 'gionniboy' Pullara <giovbat@gmail.com> $
# Docker-compose -- Build Django/Postgres/Redis/MailHog dev env based on docker containers.

version: '3.7'

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
      shm_size: "2gb"
    image: djangazzo/django:3.1
    # user: ${CURRENT_UID:-}
    env_file:
      - env-example
    volumes:
      - .:/app
    networks:
      - djangazzo
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - mailhog
    restart: unless-stopped

  postgres:
    image: postgres:11-alpine
    env_file:
      - .env
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    networks:
      - djangazzo
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:6.0.9-alpine
    networks:
      - djangazzo
    ports:
      - "6379:6379"
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:v1.0.0
    networks:
      - djangazzo
    ports:
      - "8025:8025"
    restart: unless-stopped


volumes:
  postgres_data_local: {}

networks:
  djangazzo:
