# $Id: docker-compose.yml v.0.5 $ $Date: 2018/05/10 $ $Author: GB 'gionniboy' Pullarà <giovbat@gmail.com> $

# Docker-compose -- Build Django/Postgres/MailHog dev env based on docker containers.

version: '3.6'

services:
  # build our django container
  django:
    build:
      context: .
      dockerfile: /Docker/Dockerfile.django
    environment:
      - TERM=xterm-256color
    container_name: djangazzo-web
    image: djangazzo/django:2.0.5
    command: /start.sh
    volumes:
      - .:/app
    env_file:
      - .django-env
      - .postgres-env
    networks:
      - djangazzo
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mailhog
    restart: always

  postgres:
    build:
      context: .
      dockerfile: /Docker/Dockerfile.postgres
    container_name: djangazzo-postgres
    environment:
      - TERM=xterm-256color
    image: djangazzo/postgres:9.6.9
    env_file:
      - .postgres-env
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    networks:
      - djangazzo
    ports:
      - "5432:5432"
    restart: always

  mailhog:
    image: mailhog/mailhog:v1.0.0
    networks:
      - djangazzo
    ports:
      - "8025:8025"
    restart: always


# build volumes - needed by pg-maintenance
volumes:
  postgres_data_local: {}

  # Build directives for Docker Network Bridging
networks:
  djangazzo:
